'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const workbench = fs.readFileSync(path.join(root, 'src/ai/agent-workbench.js'), 'utf8');
const styles = fs.readFileSync(path.join(root, 'src/ai/agent-workbench.css'), 'utf8');
const scene = fs.readFileSync(path.join(root, 'src/task-horizon/main/render/41-render-scene-context.js'), 'utf8');
const sidePanels = fs.readFileSync(path.join(root, 'src/task-horizon/main/render/47-render-side-panels-and-view-switching.js'), 'utf8');
const taskList = fs.readFileSync(path.join(root, 'src/task-horizon/main/task-runtime/53-list-render-and-document-loader.js'), 'utf8');
const dialogFoundation = fs.readFileSync(path.join(root, 'src/task-horizon/main/30-dialogs-and-ui-foundation.js'), 'utf8');
const externalDragRouting = fs.readFileSync(path.join(root, 'src/task-horizon/main/41-external-task-drag-routing.js'), 'utf8');
const calendarView = fs.readFileSync(path.join(root, 'calendar-view.js'), 'utf8');

assert.match(workbench, /data-agent-action="open-context-picker"/, 'context add button is missing');
assert.match(workbench, /class="tm-agent-context__control tm-agent-context__add ariaLabel"/, 'context add button must use isolated sizing styles');
assert.doesNotMatch(workbench, /block__icon[^"\n]*tm-agent-context__add/, 'context add button must not inherit SiYuan toolbar sizing');
assert.match(workbench, /data-agent-action="toggle-context-expanded"/, 'context area must provide an expand action');
assert.match(workbench, /data-agent-action="clear-context"/, 'context area must provide a clear action');
assert.match(workbench, /contextPickerScrollTop: 0/, 'context picker must track its scroll position');
assert.match(workbench, /results\.scrollTop = Math\.max\(0, Number\(runtime\.contextPickerScrollTop\)/, 'context picker must restore scroll position after rendering');
assert.match(workbench, /target\.matches\('\.tm-agent-context-picker__results'\)[\s\S]*runtime\.contextPickerScrollTop = target\.scrollTop/, 'context picker must record user scrolling');
assert.match(workbench, /PHOSPHOR_BOLD_CONTEXT_PATHS[\s\S]*plus:[\s\S]*caretUp:[\s\S]*caretDown:[\s\S]*broom:/, 'new context controls must use Phosphor bold paths');
assert.doesNotMatch(workbench, /data-agent-action="(?:open-context-picker|toggle-context-expanded)"[^\n]*xlink:href="#icon(?:Add|Up|Down)"/, 'new context controls must not use SiYuan sprite icons');
assert.match(workbench, /data-agent-action="add-current-task"/, 'current task action is missing');
assert.match(workbench, /data-agent-action="add-current-document"/, 'current document action is missing');
assert.doesNotMatch(workbench, /focusedDocumentID|syncFocusedDocumentContext/, 'the plugin workbench must not follow the focused SiYuan document');
assert.match(workbench, /action === 'add-current-document'[\s\S]*getCurrentDocId[\s\S]*contextItemSelected\('document', documentID\)[\s\S]*addContextItem\('document', documentID, '当前文档'\)/, 'the current-document button must add a stable explicit plugin context');
assert.match(workbench, /data-agent-action="add-current-view"/, 'current view action is missing');
assert.match(workbench, /taskHorizonQueryTasks[\s\S]*filters: query \? \{ keyword: query \} : \{\}/, 'task search must use structured filters');
assert.match(workbench, /taskHorizonSearchDocuments[\s\S]*keyword: query/, 'document search must use the fixed kernel RPC');
assert.match(workbench, /runtime\.context\.documentIDs\.length > 0[\s\S]*getDocumentTaskReadScope[\s\S]*mergeTaskReadScopes[\s\S]*scopeMode: runtime\.context\.documentIDs\.length \? 'documents' : 'tasks'/, 'document context must register the document\'s complete Task Horizon task scope independently of the active task-manager tab');
assert.match(workbench, /function isTaskContextID\(value\)[\s\S]*isTaskBlockID\(value\) \|\| isVirtualTaskID\(value\)[\s\S]*context\.taskIDs[\s\S]*filter\(isTaskContextID\)/, 'stored contexts must preserve real tasks and read-only recurring virtual tasks');
assert.match(workbench, /function addContextItem\(kind, id, label\)[\s\S]*kind === 'task' && !isTaskContextID\(targetID\)/, 'manually added task context must accept real and recurring virtual task IDs');
assert.match(workbench, /TASK_CONTEXT_DRAG_TYPES[\s\S]*application\/x-tm-task-ids[\s\S]*application\/x-tm-whiteboard-pool[\s\S]*application\/x-tm-whiteboard-task/, 'the workbench must recognize list and whiteboard task drag payloads');
assert.match(workbench, /application\/x-tm-task-link[\s\S]*return false/, 'task-link drags must not be mistaken for context drops');
assert.match(workbench, /function addDraggedTasksToContext\(payload\)[\s\S]*runtime\.context\.taskIDs\.push\(\.\.\.newTaskIDs\)[\s\S]*enrichContextLabels/, 'dropped tasks must be deduplicated, added to context, and label-enriched');
assert.match(workbench, /listen\('dragover'[\s\S]*isTaskContextDataTransfer[\s\S]*listen\('drop'[\s\S]*addDraggedTasksToContext/, 'the full workbench host must accept native task drops');
assert.match(workbench, /handleTaskContextDragOver,[\s\S]*clearTaskContextDropState,[\s\S]*addDraggedTasksToContext,/, 'the workbench must expose context drop hooks to pointer drag routing');
assert.match(externalDragRouting, /closest\('\.tm-agent-workbench'\)[\s\S]*type: 'agent-context'/, 'calendar pointer routing must recognize the whole agent workbench');
assert.match(externalDragRouting, /hit\.type === 'agent-context'[\s\S]*handleTaskContextDragOver[\s\S]*hit\.type === 'agent-context'[\s\S]*addDraggedTasksToContext/, 'calendar pointer drag-over and drop must both route into agent context');
assert.match(calendarView, /function updateOfficialExternalTaskDragIndicators[\s\S]*__tmHandleExternalTaskDragOver[\s\S]*function finalizeOfficialExternalTaskDragDrop[\s\S]*__tmHandleExternalTaskDrop/, 'calendar-view pointer dragging must feed the shared external drop routing used by agent context');
assert.doesNotMatch(workbench, /\/api\/search\/fullTextSearchBlock/, 'context picker must not depend on full-text block search');
assert.match(workbench, /data-agent-action="finish-context-picker"/, 'multi-select picker must provide a finish action');
assert.match(workbench, /const directTaskIDs = omitDirectTaskReferences \? \[\] : taskIDs\.filter\(isTaskBlockID\);[\s\S]*selectedBlockIDs: Array\.from\(new Set\(\[\.\.\.directTaskIDs, \.\.\.documentIDs\]\)\)/, 'small real selections may use native references, while virtual and bulk selections stay behind the complete scope token');
assert.match(workbench, /get_task_view_context 前端动作/, 'view scope must be passed to the Agent');
assert.match(workbench, /当前范围含循环虚拟实例[\s\S]*repeatinst ID 作为 taskId[\s\S]*create_schedule[\s\S]*update_schedule[\s\S]*batch_schedules[\s\S]*apply_task_operation_plan[\s\S]*scopeToken/, 'the Agent must receive complete virtual recurring schedule guidance');
assert.match(calendarView, /function isVirtualRecurringTaskScheduleItem[\s\S]*repeatinst:/, 'calendar schedules must recognize recurring virtual task IDs');
assert.match(calendarView, /collectScheduleDateFollowTargets[\s\S]*isVirtualRecurringTaskScheduleItem\(item\)/, 'virtual recurring schedules must not write dates back to read-only tasks');
assert.match(calendarView, /__tmVirtualTaskSchedule: isVirtualTaskSchedule[\s\S]*__tmTaskDateReadOnly: isVirtualTaskSchedule[\s\S]*__tmSourceTaskId: sourceTaskId/, 'virtual recurring schedules must retain read-only completion metadata in calendar events');
assert.match(calendarView, /source === 'schedule' && ext\?\.__tmVirtualTaskSchedule === true\) return true/, 'virtual recurring schedules must render as completed');
assert.match(workbench, /if \(!hasExplicitContext\)[\s\S]*enrichContextLabels/, 'opening without explicit context must preserve the current selection');
assert.match(workbench, /labels: \(Array\.isArray\(context\.labels\)[\s\S]*?item\.kind && item\.id && item\.label/, 'stored context labels must survive plugin reload');
assert.match(workbench, /async function mountSidebar[\s\S]*?runtime\.context\.taskIDs\.length \|\| runtime\.context\.documentIDs\.length\) void enrichContextLabels\(\)/, 'mounting the workbench must refresh restored context labels');
assert.match(workbench, /async function enrichContextLabels\(\)[\s\S]*?previousLabels = JSON\.stringify\(labels\)[\s\S]*?JSON\.stringify\(labels\) !== previousLabels\) scheduleSave\(\)/, 'refreshed context labels must be persisted when they change');
assert.match(workbench, /class="tm-agent-context__scrollbar"[\s\S]*?tm-agent-context__scrollbar-thumb/, 'context row must render an overlay scrollbar');
assert.match(workbench, /function syncContextScrollbar\(show = false\)[\s\S]*?items\.clientWidth[\s\S]*?items\.scrollWidth[\s\S]*?items\.scrollLeft/, 'overlay scrollbar must track the context viewport and scroll position');
assert.match(workbench, /function beginContextScrollbarDrag[\s\S]*?setPointerCapture[\s\S]*?function moveContextScrollbarDrag/, 'overlay scrollbar thumb must support pointer dragging');
assert.match(workbench, /listen\('wheel'[\s\S]*?closest\?\.\('\.tm-agent-context'\)[\s\S]*?items\.scrollLeft \+= rawDelta \* unit[\s\S]*?passive: false/, 'mouse wheel input over the context row must scroll overflowing chips horizontally');
assert.match(styles, /\.tm-agent-context-picker\s*\{/, 'context picker styles are missing');
assert.match(styles, /\.tm-agent-workbench\.is-task-drag-over \.tm-agent-task-drop-hint\s*\{[\s\S]*border-color:[\s\S]*background:[\s\S]*opacity: 1;/, 'the entire agent workbench must show a clear task drop target');
assert.match(styles, /\.tm-agent-context-picker__footer\s*\{/, 'multi-select footer styles are missing');
assert.match(styles, /\.tm-agent-context\s*\{[\s\S]*?height: 39px;[\s\S]*?min-height: 39px;/, 'context row height must stay compact');
assert.match(styles, /\.tm-agent-context\.is-expanded\s*\{[\s\S]*?height: auto;/, 'expanded context area must grow vertically');
assert.match(styles, /\.tm-agent-context:not\(\.is-expanded\) \.tm-agent-context__items::\-webkit-scrollbar\s*\{[\s\S]*?display: none;[\s\S]*?width: 0;[\s\S]*?height: 0;/, 'collapsed context row must fully hide the native scrollbar');
assert.match(styles, /\.tm-agent-context__scrollbar\s*\{[\s\S]*?grid-column: 1;[\s\S]*?grid-row: 1;[\s\S]*?height: 3px;[\s\S]*?opacity: 0;/, 'context scrollbar must overlay the item grid and stay hidden by default');
assert.match(styles, /\.tm-agent-context__scrollbar-thumb\s*\{[\s\S]*?22%[\s\S]*?transparent[\s\S]*?cursor: grab;/, 'overlay scrollbar thumb must stay subtle and draggable');
assert.match(styles, /\.tm-agent-context__chip\s*\{[\s\S]*?flex: 0 0 auto;[\s\S]*?box-sizing: border-box;/, 'context chips must retain their readable width and keep their borders inside the row height');
assert.match(styles, /\.tm-agent-context__control\s*\{[\s\S]*?width: 24px;[\s\S]*?height: 24px;/, 'context controls must stay 24px square');
assert.match(scene, /onclick="tmMultiSelectSendToAi\(\)"/, 'multi-select toolbar must provide a send-to-AI action');
assert.match(fs.readFileSync(path.join(root, 'src/task-horizon/main/30-dialogs-and-ui-foundation.js'), 'utf8'), /__tmPhosphorBoldPaths\['sparkle'\] = 'M199,125\.31/, 'send-to-AI must use the Phosphor bold sparkle path');
assert.match(sidePanels, /tmMultiSelectSendToAi[\s\S]*__tmGetMultiSelectedTaskIds\(\)[\s\S]*selectedTaskIds: taskIds/, 'send-to-AI must use the existing multi-select task IDs');
assert.match(taskList, /createSubmenu\(__tmRenderContextMenuLabel\('bot', 'AI'\), \(\) => \[\s*createItem\(__tmRenderContextMenuLabel\('sparkle', '发送到 AI'\)[\s\S]*selectedTaskIds: \[taskId\][\s\S]*draft: '请基于这 1 个已选任务继续处理：'/, 'task context AI submenu must start with the single-task send-to-AI action');
assert.match(dialogFoundation, /function __tmBuildTaskDetailMoreActions\(taskId\)[\s\S]*label: '发送到 AI'[\s\S]*icon: 'sparkle'[\s\S]*selectedTaskIds: \[tid\][\s\S]*draft: '请基于这 1 个已选任务继续处理：'/, 'task detail more menu must provide the same single-task send-to-AI action');

console.log('agent context contract tests passed');
