'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'src/task-horizon/manifest.main.json'), 'utf8'));
const policy = fs.readFileSync(path.join(root, 'src/task-horizon/main/settings/67-agent-policy-settings.js'), 'utf8');
const settings = fs.readFileSync(path.join(root, 'src/task-horizon/main/settings/60-settings-screen.js'), 'utf8');
const styles = fs.readFileSync(path.join(root, 'task-horizon.css'), 'utf8');

assert.ok(manifest.scripts.includes('main/settings/67-agent-policy-settings.js'), 'policy settings module must be part of the development source manifest');
assert.match(settings, /__tmRenderAgentPolicySettingsPanel/, 'Agent settings must render the policy editor');
assert.match(policy, /weeklyAvailability[\s\S]*fixedOccupancy[\s\S]*deadlinePriority[\s\S]*defaultCalendarID[\s\S]*customInstructions/, 'the policy editor must cover all supported rule types');
assert.match(policy, /function __tmAgentPolicyDefaultDurationDefaults\(\)[\s\S]*fallbackMinutes: 25[\s\S]*\['会议', '例会', '周会'\]/, 'default duration rules must provide the approved templates and fallback');
assert.doesNotMatch(policy, /\{ id: 'meeting'[^\n]*(?:sync|standup)/, 'meeting defaults must not include sync or standup keywords');
assert.match(policy, /任务默认时长[\s\S]*启用默认时长规则[\s\S]*同步应用到手动拖拽[\s\S]*未命中时长/, 'the policy editor must expose global duration controls');
assert.match(policy, /tmAgentPolicyUpdateDurationRule[\s\S]*tmAgentPolicyMoveDurationRule[\s\S]*tmAgentPolicyRemoveDurationRule/, 'duration rules must support editing, ordering, and removal');
assert.match(policy, /syncToManualDrag \? 'checked' : ''\} \$\{disabled\}/, 'manual drag sync must be disabled when the master switch is off');
assert.match(policy, /type="time"[\s\S]*tmAgentPolicyUpdateAvailabilityRange/, 'weekly availability must use native time pickers');
assert.match(policy, /tmAgentPolicyAddAvailabilityRange[\s\S]*tmAgentPolicyRemoveAvailabilityRange/, 'weekly availability must support adding and removing ranges');
assert.match(policy, /09:00-12:00, 14:00-18:00/, 'weekly availability must provide useful default ranges');
assert.match(policy, /__TM_AGENT_POLICY_MAX_DAILY_RANGES = 5[\s\S]*ranges\.length >= __TM_AGENT_POLICY_MAX_DAILY_RANGES/, 'weekly availability must enforce a maximum of five ranges per day');
assert.doesNotMatch(policy, /class="block__icon/, 'policy action buttons must not inherit SiYuan block toolbar opacity');
assert.match(styles, /\.tm-agent-policy-icon-button\s*\{[\s\S]*opacity: 1/, 'policy action icons must remain visible outside block toolbars');
assert.match(styles, /\.tm-agent-policy-add\s*\{[\s\S]*display: inline-flex;[\s\S]*align-items: center;[\s\S]*gap: 4px;/, 'policy add buttons must align their icon and label on one centered row');
assert.match(styles, /\.tm-agent-policy-add \.tm-agent-policy-icon\s*\{[\s\S]*display: block;[\s\S]*flex: 0 0 auto;/, 'policy add button icons must not participate in the text baseline');
assert.match(policy, /tmAgentPolicyToggleOverrideField[\s\S]*单独设置[\s\S]*继承上级，编辑后覆盖/, 'document and group overrides must explain direct editing of inherited fields');
assert.match(policy, /function __tmAgentPolicyEditableConfig\(field\)[\s\S]*__tmAgentPolicyInheritedConfig\(\)\[field\][\s\S]*tmAgentPolicySetCustomInstructions[\s\S]*__tmAgentPolicyEditableConfig\('customInstructions'\)/, 'editing an inherited field must materialize it in the selected rule');
assert.doesNotMatch(policy, /\$\{(?:enabled|priorityEnabled|calendarEnabled) \? '' : 'disabled'\}/, 'switching to an existing rule must keep its inherited fields directly editable');
assert.match(policy, /taskHorizonPreviewPolicyPatch[\s\S]*taskHorizonApplyPolicyPatch/, 'policy writes must use preview and revision-checked apply RPCs');
assert.match(policy, /window\.tmAgentPolicySave = async function[\s\S]*const preview = await __tmAgentPolicyCall\('taskHorizonPreviewPolicyPatch'[\s\S]*await __tmAgentPolicyCall\('taskHorizonApplyPolicyPatch'[\s\S]*其他安排规则已保存/, 'the other-rules save button must validate and apply its policy patch in one action');
assert.match(policy, /tmAgentPolicySaveDurationDefaults[\s\S]*patch: \{[\s\S]*durationDefaults: __tmAgentPolicyClone\(__tmAgentPolicyView\.draft\.durationDefaults[\s\S]*任务默认时长已保存/, 'duration defaults must have an independent revision-checked save path');
assert.match(policy, /tmAgentPolicySaveDurationDefaults[\s\S]*__tmAgentPolicyView\.draft\.revision = saved\.revision[\s\S]*__tmAgentPolicyView\.draft\.durationDefaults =/, 'saving duration defaults must preserve other unsaved policy fields');
assert.match(policy, /window\.tmAgentPolicySave = async function[\s\S]*__tmAgentPolicyValidate\(__tmAgentPolicyView\.draft, false\)[\s\S]*patch: \{[\s\S]*global:/, 'the other-rules save path must exclude duration validation and use a separate policy patch');
assert.doesNotMatch(policy, /window\.tmAgentPolicySave = async function[\s\S]{0,1800}patch: \{[\s\S]{0,300}durationDefaults:/, 'saving other rules must not implicitly save the duration draft');
assert.match(policy, /pendingDurationDefaults[\s\S]*__tmAgentPolicyView\.draft\.durationDefaults = pendingDurationDefaults/, 'saving other rules must retain an unsaved duration draft');
assert.doesNotMatch(policy, /预览并保存|保存前预览|确认保存|tmAgentPolicyApplyPreview|tmAgentPolicyCancelPreview/, 'policy settings must not expose a separate change-preview step');
assert.doesNotMatch(styles, /tm-agent-policy-preview/, 'obsolete policy preview styles must be removed');
assert.doesNotMatch(policy, />版本 \$\{Number\(draft\.revision\)/, 'policy revision must remain hidden during normal editing');
assert.match(policy, /STALE_REVISION[\s\S]*安排规则已在其他位置发生变化，已重新读取最新设置/, 'revision conflicts must be explained when they occur');
assert.match(policy, /tmAgentPolicyPickDocumentOverride[\s\S]*__tmOpenDocSearchPrompt\('选择文档'/, 'document policy scopes must use the searchable document picker');
assert.doesNotMatch(policy, /keywordClassification|关键词分类|tmAgentPolicy(?:Add|Update|Remove)Classification/, 'keyword classification must not remain in policy settings');
assert.match(policy, /自定义要求[\s\S]*textarea[\s\S]*maxlength="4000"[\s\S]*tmAgentPolicySetCustomInstructions/, 'policy settings must provide a bounded custom-instructions textarea');
assert.match(policy, /documentOverrides[\s\S]*groupOverrides[\s\S]*添加文档规则[\s\S]*添加文档分组规则/, 'policy settings must support document and document-group scopes');
assert.match(policy, /deletedDocumentOverrides[\s\S]*documentOverrides\[id\] = null[\s\S]*deletedGroupOverrides[\s\S]*groupOverrides\[id\] = null/, 'removing document or group rules must produce explicit delete patches');
assert.doesNotMatch(policy, /清单/, 'policy settings must consistently use document terminology');
assert.match(styles, /\.tm-agent-policy-group\s*\{[\s\S]*border-top: 1px solid var\(--tm-border-color\)/, 'policy sections must use flat native dividers');
assert.match(styles, /\.tm-agent-policy-duration-defaults\s*\{[\s\S]*border: 1px solid[\s\S]*background:/, 'duration defaults must read as a distinct flat settings region');
assert.match(styles, /\.tm-agent-policy-duration-footer\s*\{[\s\S]*justify-content: space-between/, 'duration actions must keep add and independent save commands distinct');
assert.match(styles, /@media \(max-width: 720px\)[\s\S]*\.tm-agent-policy-duration-footer[\s\S]*flex-wrap: wrap/, 'duration actions must wrap safely on narrow settings panels');
assert.match(styles, /\.tm-agent-policy-scope__add[\s\S]*display: inline-flex[\s\S]*flex-wrap: wrap/, 'policy scope add controls must stay aligned and wrap responsively');
assert.match(styles, /\.tm-agent-policy-instructions\s*\{[\s\S]*width: 100%;[\s\S]*resize: vertical;/, 'custom instructions must use a full-width resizable text field');
assert.doesNotMatch(styles, /\.tm-agent-policy[^\{]*\{[^}]*box-shadow:/, 'persistent policy settings must remain flat');
assert.match(styles, /\.tm-agent-policy-duration-row\s*\{[\s\S]*grid-template-areas:[\s\S]*\.tm-agent-policy-duration-row__keywords/, 'duration rules must use a stable responsive grid');
assert.match(styles, /@media \(max-width: 720px\)[\s\S]*\.tm-agent-policy-duration-row[\s\S]*"keywords keywords"/, 'duration rules must adapt without hiding controls on narrow screens');

console.log('agent policy settings contract tests passed');
