const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const motionPath = path.join(root, 'src', 'task-horizon', 'main', '18-collapse-motion-runtime.js');
const manifestPath = path.join(root, 'src', 'task-horizon', 'manifest.main.json');
const renderRuntimePath = path.join(root, 'src', 'task-horizon', 'main', '40-render-runtime.js');
const apiRuntimePath = path.join(root, 'src', 'task-horizon', 'main', '20-api-and-runtime-services.js');
const uiFoundationPath = path.join(root, 'src', 'task-horizon', 'main', '30-dialogs-and-ui-foundation.js');
const settingsActionsPath = path.join(root, 'src', 'task-horizon', 'main', 'settings', '70-doc-group-and-settings-actions.js');
const sceneContextPath = path.join(root, 'src', 'task-horizon', 'main', 'render', '41-render-scene-context.js');
const checklistRendererPath = path.join(root, 'src', 'task-horizon', 'main', 'render', '42-render-list-and-checklist-body.js');
const stylesPath = path.join(root, 'task-horizon.css');
const whiteboardRuntimePath = path.join(root, 'src', 'task-horizon', 'main', 'render', '49-render-whiteboard-interactions.js');
const lifecyclePath = path.join(root, 'src', 'task-horizon', 'main', 'shell', '80-shell-lifecycle.js');
const motion = fs.readFileSync(motionPath, 'utf8');
const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
const renderRuntime = fs.readFileSync(renderRuntimePath, 'utf8');
const apiRuntime = fs.readFileSync(apiRuntimePath, 'utf8');
const uiFoundation = fs.readFileSync(uiFoundationPath, 'utf8');
const settingsActions = fs.readFileSync(settingsActionsPath, 'utf8');
const sceneContext = fs.readFileSync(sceneContextPath, 'utf8');
const checklistRenderer = fs.readFileSync(checklistRendererPath, 'utf8');
const styles = fs.readFileSync(stylesPath, 'utf8');
const whiteboardRuntime = fs.readFileSync(whiteboardRuntimePath, 'utf8');
const lifecycle = fs.readFileSync(lifecyclePath, 'utf8');

assert.match(motion, /const rootStates = new WeakMap\(\)/, 'motion state must not be stored on the shared view state');
assert.match(motion, /const activeElements = new WeakMap\(\)/, 'element animations must have a cancelable weak registry');
assert.doesNotMatch(motion, /__tmCollapseMotionLog|logSequence|\[TaskHorizon\]\[CollapseMotion/, 'collapse diagnostics must stay removed from production motion');
assert.doesNotMatch(motion, /Array\.from\(surface\.container\.querySelectorAll/, 'visible capture must not duplicate the complete candidate list');
assert.match(motion, /prefers-reduced-motion: reduce/, 'reduced motion must disable structural animation');
assert.match(motion, /maxVisibleNodes: 32/, 'layout animation must cap visible nodes');
assert.match(motion, /maxTimelineNodes: 64/, 'timeline must keep a separate two-surface cap');
assert.match(motion, /Math\.floor\(config\.maxTimelineNodes \/ 2\)/, 'timeline surface caps must derive from the shared total budget');
assert.match(motion, /maxDisclosureItems: 24/, 'checklist FLIP capture must keep the shared twenty-four-item budget');
assert.match(motion, /profile === 'checklist' \? config\.maxDisclosureItems : config\.maxVisibleNodes/, 'checklist FLIP must use the twenty-four-item cap');
assert.match(motion, /options\.allowDuringScroll === true[\s\S]*?busySelector/, 'local disclosure motion must be able to ignore stale scroll-active markers');
assert.match(motion, /allowDuringScroll: options\.allowDuringScroll === true[\s\S]*?__tmCollapseMotionCanAnimate\(root, pending\)/, 'FLIP playback must preserve explicit-toggle scroll policy');
assert.doesNotMatch(motion, /disclosureMode|maxDisclosureViewportRatio|content\.scrollHeight|willChange: ['"]height|\{ height:/, 'structural motion must not animate or measure container height');
assert.match(motion, /const mode = requestedMode === 'layout' \? 'layout' : 'none';[\s\S]*?content\.style\.removeProperty\('height'\)/, 'visibility commits must only choose FLIP or immediate mode');
assert.match(motion, /animation\.oncancel = \(\) => entry\.finish\(false\)/, 'canceled animations must share the cleanup path');
assert.match(motion, /const pending = runtime\.pendingLayout;[\s\S]*?pending\?\.settle\?\.\(false\)/, 'canceling a pending layout must settle its lifecycle callback');
assert.match(motion, /settle\(completed\) \{[\s\S]*?options\.onSettled\?\.\(completed === true\)/, 'layout transactions must expose one guarded settle callback');
assert.match(motion, /const animateLayout =[\s\S]*?onFinish: \(\) => finish\(true\)[\s\S]*?onCancel: \(\) => finish\(false\)[\s\S]*?pending\.settle\?\.\(completed\)/, 'layout settlement must wait for compositor animations to finish or cancel');
assert.match(motion, /pending\.profile === 'checklist' && pending\.action === 'expand'[\s\S]*?pending\.getClipBoundary\?\.\(\)[\s\S]*?clipBoundaryBottom/, 'checklist expansion must resolve one branch boundary from the committed layout');
assert.match(motion, /const clipTop = clipBoundaryBottom[\s\S]*?previous\.rect\.top[\s\S]*?from\.clipPath = `inset\(\$\{clipTop\}px 0 0 0\)`[\s\S]*?willChange: clipTop > 0 \? 'transform, clip-path' : 'transform'/, 'later checklist rows must be clipped until they emerge below the expanded branch');
assert.doesNotMatch(motion, /activeDisclosureViewports|isDisclosureViewportActive|__tmCollapseMotionHoldDisclosureViewport/, 'removed height motion must not leave viewport bookkeeping behind');
assert.doesNotMatch(motion, /cloneNode|position\s*=\s*['"]fixed/, 'layout motion must not create fixed row clones');

const motionIndex = manifest.scripts.indexOf('main/18-collapse-motion-runtime.js');
const apiIndex = manifest.scripts.indexOf('main/20-api-and-runtime-services.js');
assert.ok(motionIndex > -1 && motionIndex < apiIndex, 'motion runtime must load before API and render consumers');

const taskCollapseStart = renderRuntime.indexOf('function __tmSetKanbanTaskCollapsedInDom');
const groupCollapseStart = renderRuntime.indexOf('function __tmSetKanbanGroupCollapsedInDom');
const columnCollapseStart = renderRuntime.indexOf('function __tmSetKanbanColumnCollapsedInDom');
const taskCollapse = renderRuntime.slice(taskCollapseStart, groupCollapseStart);
const groupCollapse = renderRuntime.slice(groupCollapseStart, columnCollapseStart);
const columnCollapse = renderRuntime.slice(columnCollapseStart, renderRuntime.indexOf('window.tmKanbanToggleCollapse'));
assert.match(taskCollapse, /__tmSetKanbanDisclosureContent/, 'kanban task groups must use disclosure motion');
assert.match(groupCollapse, /__tmSetKanbanDisclosureContent/, 'kanban content groups must use disclosure motion');
assert.doesNotMatch(columnCollapse, /__tmCollapseMotion|__tmSetKanbanDisclosureContent/, 'kanban column collapse must remain immediate');
const kanbanDisclosureStart = renderRuntime.indexOf('function __tmSetKanbanDisclosureContent');
const kanbanDisclosureEnd = renderRuntime.indexOf('function __tmSetKanbanTaskCollapsedInDom', kanbanDisclosureStart);
const kanbanDisclosure = renderRuntime.slice(kanbanDisclosureStart, kanbanDisclosureEnd);
assert.match(kanbanDisclosure, /beginLayout\(state\.modal,[\s\S]*?profile: 'kanban-column'[\s\S]*?scope: columnBody[\s\S]*?mode = 'layout'/, 'kanban disclosure must use column-scoped FLIP motion');
assert.doesNotMatch(kanbanDisclosure, /disclosureMode|itemSelector|logContext/, 'kanban disclosure must avoid per-frame height animation setup');
assert.match(apiRuntime, /function __tmReconcileChecklistCollapseList[\s\S]*?currentTaskNodes\.get\(taskId\)[\s\S]*?currentGroupNodes\.get\(groupKey\)/, 'checklist collapse must preserve unaffected task and group nodes');
assert.match(apiRuntime, /function __tmInsertChecklistTaskBranchFragment[\s\S]*?tmChecklistBranchFragment[\s\S]*?branchNodes\.forEach\(\(node\) => parent\.insertBefore/, 'cold checklist task expansion must insert only the rendered target branch');
assert.match(apiRuntime, /if \(opts\.listOnly === true\)[\s\S]*?__tmReconcileChecklistCollapseList\(currentItems, nextItems, opts\)/, 'checklist collapse must use the targeted node reconciler');
assert.match(apiRuntime, /renderBodyHtml\(\{ taskBranchId \}\)[\s\S]*?branchFragment[\s\S]*?__tmInsertChecklistTaskBranchFragment/, 'small cold task expansion must request and consume a branch-only render');
assert.match(apiRuntime, /if \(branchFragment\) \{[\s\S]*?__tmScheduleIdleTask\(finishBranchRefresh, 260\)[\s\S]*?return true;[\s\S]*?__tmRefreshChecklistSelectionInPlace/, 'branch-only expansion must defer full-list enhancement work until after the interaction');
assert.ok(apiRuntime.indexOf('if (opts.listOnly === true)') < apiRuntime.indexOf('if (checklistProjectionTaskIds.length > 0'), 'explicit checklist collapse must outrank concurrent projection refresh branches');
const checklistDisclosureStart = apiRuntime.indexOf('function __tmAnimateChecklistDisclosure');
const checklistDisclosureEnd = apiRuntime.indexOf('function __tmTryRefreshChecklistProjectionGroups', checklistDisclosureStart);
assert.ok(checklistDisclosureStart > -1 && checklistDisclosureEnd > checklistDisclosureStart, 'checklist disclosure implementation must remain discoverable');
const checklistDisclosure = apiRuntime.slice(checklistDisclosureStart, checklistDisclosureEnd);
assert.match(checklistDisclosure, /__tmCollapseMotion\.beginLayout\(modal,[\s\S]*?profile: 'checklist'[\s\S]*?allowDuringScroll: true[\s\S]*?motionMode = 'layout'/, 'checklist task and group collapse must use local FLIP motion');
assert.match(checklistDisclosure, /onSettled: finishDisclosure/, 'checklist disclosure cleanup must follow the shared FLIP lifecycle');
assert.match(checklistDisclosure, /getClipBoundary: \(\) => context\?\.content \|\| null/, 'checklist FLIP must use the retained branch wrapper as its clip boundary');
assert.ok(checklistDisclosure.indexOf('__tmCollapseMotion.beginLayout') < checklistDisclosure.indexOf('commit();'), 'checklist FLIP must capture positions before cold branch insertion');
assert.match(checklistDisclosure, /forceMode: motionMode[\s\S]*?queueMicrotask\(\(\) => \{[\s\S]*?__tmCollapseMotion\.playLayout\(modal\)/, 'checklist visibility commit must be followed by FLIP playback');
assert.doesNotMatch(checklistDisclosure, /disclosureMode|itemSelector|boundedItemCount|requestAnimationFrame|logContext/, 'checklist FLIP must not retain height-animation setup or delayed first paint');
assert.match(apiRuntime, /persistedWrapper[\s\S]*?tmChecklistDisclosureKind[\s\S]*?tmChecklistDisclosureKey/, 'collapsed checklist branches must remain mounted for direct expansion');
assert.match(checklistDisclosure, /action === 'expand' && !context\?\.content\?\.hidden[\s\S]*?commit\(\)[\s\S]*?context = __tmGetChecklistDisclosureContext/, 'checklist expansion must render only when no mounted collapsed branch is available');
assert.match(checklistDisclosure, /let coldExpansion = false;[\s\S]*?commit\(\);[\s\S]*?coldExpansion = true;/, 'checklist expansion must distinguish newly rendered branches from mounted warm branches');
assert.match(checklistDisclosure, /__tmSyncCurrentViewDomRenderSignature\('checklist'\);[\s\S]*?const startDisclosure = \(\) =>/, 'checklist state signatures must be committed before cold expansion is scheduled');
assert.match(checklistDisclosure, /state\.modal !== modal[\s\S]*?state\.viewMode[\s\S]*?!modal\.isConnected[\s\S]*?!context\.content\.isConnected[\s\S]*?isCollapsedNow\(\)\) \{[\s\S]*?__tmCollapseMotion\.cancel\(modal\)/, 'deferred checklist expansion must ignore stale modal, view, DOM, and collapse state');
assert.match(checklistDisclosure, /const startDisclosure = \(\) => \{[\s\S]*?__tmCollapseMotion\.setDisclosure/, 'checklist cold and warm paths must share one disclosure start implementation');
assert.match(checklistDisclosure, /const finishDisclosure = \(\) => \{[\s\S]*?__tmUnwrapChecklistDisclosure\(context\)[\s\S]*?__tmSyncCurrentViewDomRenderSignature\('checklist'\)/, 'checklist disclosure completion must unwrap expanded content after FLIP settles');
assert.match(checklistDisclosure, /const deferFinish = action === 'expand' && motionMode === 'layout';[\s\S]*?if \(!deferFinish\) finishDisclosure\(\)/, 'animated checklist expansion must retain its boundary wrapper only while FLIP is active');
assert.match(checklistDisclosure, /__tmCollapseMotion\.cancel\(modal\)/, 'rapid checklist reversals must cancel the previous disclosure transaction');
assert.match(apiRuntime, /const persistedWrapper = anchor\.nextElementSibling;[\s\S]*?return \{ anchor, content: persistedWrapper, wrapper: true \}/, 'rapid checklist reversals must reuse the mounted disclosure branch');
assert.doesNotMatch(apiRuntime, /querySelectorAll\('\.tm-checklist-disclosure'\)[\s\S]*?__tmUnwrapChecklistDisclosure/, 'rapid checklist reversals must not discard mounted collapsed branches');
assert.match(sceneContext, /taskBranchId: String\(renderOptions\?\.taskBranchId \|\| ''\)\.trim\(\)/, 'checklist scene context must forward branch-only render requests');
assert.match(checklistRenderer, /const taskBranchId = String\(opts\.taskBranchId \|\| ''\)\.trim\(\);[\s\S]*?descendantCount > 0 && descendantCount <= disclosureLimit[\s\S]*?data-tm-checklist-branch-fragment/, 'branch-only rendering must remain limited to the shared small-disclosure budget');
assert.doesNotMatch(uiFoundation, /isDisclosureMotionActive|isDisclosureViewportActive|__tmCollapseMotionSettled/, 'custom scrollbars must not retain height-animation coordination hooks');
assert.match(uiFoundation, /function __tmBindTimelineScrollVisibility[\s\S]*?onScroll: \(\) => \{[\s\S]*?__tmCancelAnimationsWithin\(modal\)/, 'timeline scrolling must cancel active two-surface FLIP animations immediately');
assert.match(settingsActions, /if \(!isKanban && !isChecklist\)[\s\S]*?__tmPrepareFlipAnimation/, 'checklist collapse must not enter the full-list FLIP path');
assert.match(settingsActions, /__tmAnimateChecklistDisclosure\('group', k0, action, \{ animate: !skipAnim \}\)/, 'checklist groups must use local disclosure motion');
assert.match(settingsActions, /__tmAnimateChecklistDisclosure\('task', key, action, \{ animate: !skipAnim \}\)/, 'checklist task branches must use local disclosure motion');
assert.match(styles, /\.tm-checklist-disclosure[\s\S]*?flex-direction: column/, 'temporary checklist disclosure wrappers must preserve vertical list layout');
assert.doesNotMatch(styles, /tm-checklist-disclosure--revealing|tm-checklist-group-card--revealing|tm-checklist-disclosure-mask-bg/, 'checklist FLIP clipping must not cover document accent colors with temporary backgrounds');
assert.match(styles, /\.tm-checklist-disclosure\[hidden\],[\s\S]*?\.tm-checklist-group-card-items\[hidden\][\s\S]*?display: none !important/, 'mounted checklist branches must have an explicit hidden layout state');
assert.match(styles, /@supports \(content-visibility: auto\)[\s\S]*?\.tm-checklist-disclosure > \.tm-checklist-item \{[\s\S]*?content-visibility: visible;[\s\S]*?contain-intrinsic-size: none;/, 'cold checklist disclosure rows must paint during their first expansion');
assert.match(whiteboardRuntime, /tmWhiteboardTogglePoolSection[\s\S]*?beginLayout\(state\.modal,[\s\S]*?profile: 'whiteboard-pool'[\s\S]*?forceMode: motionMode[\s\S]*?playLayout\(state\.modal\)/, 'whiteboard pool groups must use scoped FLIP motion');
assert.doesNotMatch(whiteboardRuntime.slice(whiteboardRuntime.indexOf('window.tmWhiteboardTogglePoolSection'), whiteboardRuntime.indexOf('function __tmBuildWhiteboardPointerInfoFromBody')), /disclosureMode|itemSelector/, 'whiteboard pool collapse must not retain height-animation setup');
assert.match(whiteboardRuntime, /tmWhiteboardToggleTaskCollapse[\s\S]*?fadeClip[\s\S]*?tm-whiteboard-edges/, 'whiteboard tasks must use lightweight card and edge transitions');
assert.match(lifecycle, /__tmCollapseMotion\.cancel\(state\.modal\)[\s\S]*?state\.modal\.remove\(\)/, 'modal teardown must cancel active structural animations before removal');

console.log('collapse motion runtime contract tests passed');
