'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const listRuntime = fs.readFileSync(path.join(root, 'src/task-horizon/main/task-runtime/53-list-render-and-document-loader.js'), 'utf8');
const checklistRuntime = fs.readFileSync(path.join(root, 'src/task-horizon/main/render/42-render-list-and-checklist-body.js'), 'utf8');
const viewSwitchRuntime = fs.readFileSync(path.join(root, 'src/task-horizon/main/render/47-render-side-panels-and-view-switching.js'), 'utf8');
const shellControlsRuntime = fs.readFileSync(path.join(root, 'src/task-horizon/main/render/45-render-shell-controls-and-resize.js'), 'utf8');
const renderRuntime = fs.readFileSync(path.join(root, 'src/task-horizon/main/40-render-runtime.js'), 'utf8');
const sceneRuntime = fs.readFileSync(path.join(root, 'src/task-horizon/main/render/41-render-scene-context.js'), 'utf8');
const kanbanRuntime = fs.readFileSync(path.join(root, 'src/task-horizon/main/render/43-render-timeline-kanban-calendar-body.js'), 'utf8');
const dialogRuntime = fs.readFileSync(path.join(root, 'src/task-horizon/main/30-dialogs-and-ui-foundation.js'), 'utf8');
const servicesRuntime = fs.readFileSync(path.join(root, 'src/task-horizon/main/20-api-and-runtime-services.js'), 'utf8');
const ganttRuntime = fs.readFileSync(path.join(root, 'src/task-horizon/main/shell/82-gantt-runtime.js'), 'utf8');
const styles = fs.readFileSync(path.join(root, 'task-horizon.css'), 'utf8');
const segment = (source, start, end) => {
    const from = source.indexOf(start);
    const to = source.indexOf(end, from + start.length);
    assert.notEqual(from, -1, `missing segment start: ${start}`);
    assert.notEqual(to, -1, `missing segment end: ${end}`);
    return source.slice(from, to);
};
const mobileSwitchScheduler = segment(shellControlsRuntime, 'function __tmScheduleMobileBottomViewSwitch', 'window.tmSwitchViewModeFromMobileBottomNav');
const viewSwitchCommitScheduler = segment(viewSwitchRuntime, 'function __tmScheduleViewSwitchCommit', 'function __tmMountCalendarViewRoot');

assert.match(listRuntime, /const virtualThreshold = state\.__tmSnapshotFirstRenderLimitMode \? 0 : 50;/, 'large list views must use the existing incremental render window');
assert.match(listRuntime, /const listStep = Math\.max\(20,/, 'progressive table batches must preserve the 20-row minimum');
assert.match(checklistRuntime, /const checklistVirtualThreshold = state\.__tmSnapshotFirstRenderLimitMode \? 0 : 50;/, 'large checklist views must use the existing incremental render window');
assert.doesNotMatch(checklistRuntime, /Object\.values\(state\.flatTasks/, 'checklist rendering must not scan and mutate the full task store');
assert.doesNotMatch(checklistRuntime, /visibleDateAliases|writeVisibleDateAlias/, 'visible date aliases must be normalized at the data boundary, not during rendering');
assert.match(checklistRuntime, /onclick="tmChecklistLoadMoreRows\(event\)"/, 'checklist load-more must use its own render-window policy');
assert.match(viewSwitchRuntime, /__tmStartProgressiveViewRender\(next\)[\s\S]*__tmScheduleProgressiveViewRender\(next, progressiveJob\)/, 'large list view switches must append rows progressively after the first paint');
assert.match(kanbanRuntime, /progressiveKanbanRender[\s\S]*kanbanProgressiveJob\.batchSize[\s\S]*renderColumnListHtml\(progressiveColumnLimit\)/, 'kanban switches must render the first batch independently in every column');
assert.match(kanbanRuntime, /const initialColumnRender = isColumnCollapsed\s*\? \{ html: '', hasMore: false, rendered: 0 \}/, 'collapsed kanban columns must skip card rendering and progressive registration');
assert.match(kanbanRuntime, /__tmRegisterKanbanProgressiveColumn[\s\S]*progressiveColumnLimit \+=[\s\S]*body\.innerHTML = nextColumnRender\.html/, 'expanded kanban columns must load later batches through independent column bodies');
assert.match(viewSwitchRuntime, /function __tmShowViewSwitchPendingShell[\s\S]*?__tmSyncBodyOnlyViewSwitcherButtons\(modal, nextMode\)[\s\S]*?tm-main-stage--view-switch-pending[\s\S]*?aria-busy/, 'view switches must expose the target UI state before rendering its body');
assert.match(mobileSwitchScheduler, /window\.tmSwitchViewMode\(next\)/, 'mobile navigation must enter the shared switch pipeline without an extra frame delay');
assert.doesNotMatch(mobileSwitchScheduler, /requestAnimationFrame/, 'mobile navigation must not add another requestAnimationFrame queue before switching');
assert.match(viewSwitchCommitScheduler, /requestAnimationFrame\(\(\) => \{[\s\S]*?setTimeout\(run, 0\)/, 'view construction must start after one feedback paint, not after repeated animation frames');
assert.doesNotMatch(viewSwitchCommitScheduler, /__tmScheduleAfterNextPaint/, 'the switch commit must own its single feedback-paint boundary');
assert.match(viewSwitchRuntime, /function __tmScheduleViewSwitchCommit[\s\S]*?__tmViewSwitchCommitGeneration[\s\S]*?state\.viewMode[\s\S]*?callback\(\)/, 'stale deferred view switches must not commit');
assert.match(viewSwitchRuntime, /const pendingModal = __tmShowViewSwitchPendingShell\(next\);[\s\S]*?__tmScheduleViewSwitchCommit\(generation, next,[\s\S]*?__tmStartProgressiveViewRender\(next\)[\s\S]*?__tmScheduleProgressiveViewRender\(next, progressiveJob\)/, 'filtering, initial rendering, and progressive batches must start only after the interface-first paint');
assert.match(viewSwitchRuntime, /__tmMarkHighPriorityInteraction\('view-switch', mobileLike \? 460 : 240\);/, 'desktop and mobile view switches must defer non-critical render work');
assert.match(viewSwitchRuntime, /state\.uiAnimKind = '';\s*state\.uiAnimTs = 0;/, 'all task view switches must render without transition animation');
assert.doesNotMatch(viewSwitchRuntime, /reduceSwitchMotion|prevIdx|nextIdx/, 'view switching must not retain task-count-specific animation branches');
assert.match(viewSwitchRuntime, /__TM_BODY_ONLY_VIEW_SWITCH_MODES = new Set\(\['list', 'checklist', 'timeline', 'kanban', 'calendar', 'whiteboard'\]\)/, 'all task views must keep the persistent shell during a switch');
assert.match(viewSwitchRuntime, /function __tmTrySwitchViewBodyInPlace[\s\S]*?document\.createElement\('div'\)[\s\S]*?stage\.replaceWith\(nextStage\)[\s\S]*?modal\.setAttribute\('data-tm-render-mode', nextMode\)/, 'task views must build the next stage off-DOM and commit it atomically');
assert.match(viewSwitchRuntime, /function __tmReleaseDetachedViewStage[\s\S]*?stage\.replaceChildren\(\)[\s\S]*?requestIdleCallback\(clear,/, 'detached large view trees must be cleared outside the switch commit');
assert.doesNotMatch(viewSwitchRuntime, /function __tmKeepPreviousStageUntilTargetPaint/, 'an off-DOM target stage must replace the old stage directly instead of creating an overlapping cover layer');
assert.doesNotMatch(viewSwitchRuntime, /previousStageHost|previousStageRect|keepPreviousStage/, 'the switch path must not retain detached view stages inside the live shell');
assert.doesNotMatch(viewSwitchRuntime, /stage\.innerHTML\s*=/, 'stage switching must not synchronously destroy the live large subtree');
assert.match(viewSwitchRuntime, /forceFullRender \|\| !__tmTrySwitchViewBodyInPlace\(renderedMode, next\)[\s\S]*?__tmPreserveShellDuringViewSwitchRender = true;[\s\S]*?try \{ render\(\); \} finally \{ state\.__tmPreserveShellDuringViewSwitchRender = false; \}/, 'full-render fallbacks must preserve the visible shell until the replacement is mounted');
assert.doesNotMatch(viewSwitchRuntime, /state\.homepageOpen \|\| state\.attachmentLibraryOpen \|\| __tmIsMobileDevice/, 'mobile and dock hosts must keep the shell and bottom navigation during task-view switches');
assert.doesNotMatch(viewSwitchRuntime, /if \(__tmShouldShowCalendarSideDock\(\) \|\|/, 'mobile task-view switches must not fall back merely because the desktop calendar dock setting is enabled');
assert.doesNotMatch(viewSwitchRuntime, /scene\.showTaskDetailSheet\s*\|\|/, 'mobile task views must not full-render merely because the task-detail sheet is supported');
assert.match(viewSwitchRuntime, /isMobile,[\s\S]*?isDockHost,[\s\S]*?isRuntimeMobile,[\s\S]*?isLandscape,[\s\S]*?isDesktopNarrow,/, 'stage-only scene construction must use the live host flags');
assert.match(sceneRuntime, /const __tmTimelineFullRowModel = renderMode === 'timeline' \? __tmBuildTaskRowModel\(\) : null;[\s\S]*?__tmSliceTaskRowModelByTaskWindow/, 'timeline switches must build one full row model and slice it for the first batch');
assert.match(viewSwitchRuntime, /__tmRerenderTimelineInPlace\(modal, \{[\s\S]*?rowModel: scene\?\.timelineRowModel,[\s\S]*?reuseLeftRows: true/, 'timeline stage binding must reuse the left rows produced by the scene');
assert.match(servicesRuntime, /window\.tmTimelineLoadMoreRows[\s\S]*?__tmSliceTaskRowModelByTaskWindow\(fullRowModel, grown\.previousLimit, grown\.limit\)[\s\S]*?appendOnly: true/, 'timeline progressive rendering must append only the next row-model slice');
assert.match(ganttRuntime, /const rangeRowModel =[\s\S]*?const appendOnly =[\s\S]*?if \(appendOnly\)[\s\S]*?inner\.appendChild\(row\)/, 'Gantt rendering must keep a stable full range while appending only batch rows');
assert.doesNotMatch(`${servicesRuntime}\n${renderRuntime}`, /syncRowHeights|syncRowHeightsOnce/, 'timeline rendering must use fixed row heights without forced per-row layout reads');
assert.match(renderRuntime, /data-tm-view-toolbar-extra="1"/, 'the persistent shell must expose a stable slot for view-specific toolbar controls');
assert.match(viewSwitchRuntime, /function __tmMountCalendarViewRoot/, 'calendar mounting must be reusable by the full renderer and the stage switch path');
assert.match(renderRuntime, /__tmMountCalendarViewRoot\(state\.modal/, 'full rendering must reuse the calendar mount helper');
assert.match(viewSwitchRuntime, /mode === 'whiteboard'[\s\S]*?__tmBindWhiteboardViewportInput[\s\S]*?__tmScheduleWhiteboardEdgeRedraw/, 'whiteboard stage switches must bind its existing viewport lifecycle');
assert.match(renderRuntime, /const useSoftSwap = isViewSwitchAnim \|\| state\.__tmPreserveShellDuringViewSwitchRender === true;/, 'calendar and whiteboard fallbacks must use the existing non-blank shell swap lifecycle');
assert.match(renderRuntime, /__tmBindTimelineStageInteractions\(state\.modal\)/, 'full rendering and the fast path must share timeline stage interaction binding');
assert.match(renderRuntime, /kind === 'from-left' \? ' tm-stage-anim--from-left' : ''/, 'an empty animation kind must not fall through to the vertical stage animation');
assert.doesNotMatch(styles, /tmViewFadeIn|tm-stage-anim--fade/, 'the removed large-view fade must not leave dead CSS behind');
assert.doesNotMatch(styles, /--tm-timeline-row-height/, 'timeline must inherit the same row-height token as the table view');
assert.doesNotMatch(servicesRuntime, /setTimelineRowHeight|--tm-timeline-row-height/, 'appearance settings must not maintain a separate timeline row height');
assert.match(styles, /#tmTimelineLeftTable tbody tr \{[\s\S]*?height: var\(--tm-row-height\);[\s\S]*?min-height: var\(--tm-row-height\);[\s\S]*?max-height: var\(--tm-row-height\);/, 'timeline left rows must share the fixed Gantt row height');
assert.match(styles, /\.tm-body--list \.tm-table \.tm-group-row \.tm-group-sticky \{[^}]*box-shadow:\s*none;/, 'table group labels must not draw a short underline inside the full row separator');
assert.match(styles, /\.tm-body--timeline #tmTimelineLeftTable tbody td \{[^}]*border-bottom:\s*none;[^}]*box-shadow:\s*inset 0 -1px 0 var\(--tm-table-border-color\);/, 'timeline table cells must use an inset separator so collapsed table borders cannot enlarge rows');
assert.doesNotMatch(styles, /\.tm-body--timeline[^}]*\.tm-group-row td\s*\{/, 'timeline group rows must reuse the table view row geometry without a local override');
assert.match(ganttRuntime, /tm-gantt-row tm-gantt-row--group[\s\S]*?height:var\(--tm-row-height\);min-height:var\(--tm-row-height\);max-height:var\(--tm-row-height\);/, 'Gantt group rows must use the same row-height token as table group rows');
assert.match(styles, /\.tm-gantt-row\s*\{[^}]*box-shadow:\s*inset 0 -1px 0 var\(--tm-table-border-color\);/, 'Gantt rows must draw the same inset separator without changing row geometry');
assert.match(styles, /\.tm-main-stage\.tm-main-stage--view-switch-pending \{[\s\S]*?pointer-events: none;/, 'the pending view must remain visible while preventing stale interactions');
assert.doesNotMatch(styles, /tm-main-stage--view-switch-pending::after/, 'the pending view must not be covered by a blank paint layer');
assert.doesNotMatch(styles, /\.tm-main-stage\.tm-main-stage--view-switch-pending \{[^}]*(?:background|opacity|visibility|z-index)\s*:/, 'pending styles must not hide the old view or overlap the mobile bottom navigation');
assert.match(dialogRuntime, /__tmScheduleDocGroupSwitchVerifyAfterFirstPaint\(\{[\s\S]*?source: 'switch-doc-group:snapshot-verify',[\s\S]*?scopeVerifyTtlMs: 60000/, 'snapshot-backed group switches must schedule lightweight group and task verification after first paint');
assert.doesNotMatch(dialogRuntime, /snapshotRendered\)[\s\S]*?await loadSelectedDocuments\([\s\S]*?source: 'switch-doc-group:full:snapshot'/, 'snapshot-backed group switches must not synchronously rebuild the full view');
assert.match(dialogRuntime, /const deferForScroll = __tmShouldDeferMainViewRefreshForActiveScroll\([\s\S]*?__tmScheduleIdleTask\(run, 120\)/, 'silent snapshot verification must wait until active scrolling is quiet');
assert.doesNotMatch(dialogRuntime, /source: 'switch-doc-group:snapshot-cache'/, 'group switching must not use the unconditional full task snapshot verifier');
assert.match(styles, /\.tm-table td \{[\s\S]*?border-bottom: 1px solid var\(--tm-table-border-color\);[\s\S]*?box-shadow: none;/, 'ordinary table cells must use the cheaper border separator');
assert.match(styles, /\.tm-body\.tm-body--list #tmTaskTable tbody tr\[data-id\] \{[\s\S]*?content-visibility: auto;[\s\S]*?contain-intrinsic-size: auto var\(--tm-row-height\);/, 'large table views must skip rendering offscreen task row contents');
assert.match(styles, /\.tm-kanban-card:not\(\.tm-kanban-card--sub\) \{[\s\S]*?content-visibility: auto;[\s\S]*?contain-intrinsic-size: auto 148px;/, 'kanban content visibility must remain limited to root cards');
assert.doesNotMatch(styles, /(?:tm-modal--mobile|tm-modal--dock)[^{]*\.tm-kanban-card\s*(?:,|\{)[^}]*content-visibility:\s*auto;/, 'mobile kanban content visibility must not target nested subtask cards');
assert.match(styles, /\.tm-kanban--clean \.tm-kanban-subtask-row\.tm-kanban-card \{[\s\S]*?content-visibility: visible;[\s\S]*?contain-intrinsic-size: none;/, 'nested kanban cards must bypass Android WebView content-visibility placeholders');

console.log('large snapshot view switch performance contract tests passed');
